- KWNotice.xcodeproj/project.pbxproj
- KWNotice/Assets.xcassets/AccentColor.colorset/Contents.json
- KWNotice/Setting/Setting.swift
- KWNotice/Setting/SettingView.swift
> Develop Setting UI

- KWNotice.xcodeproj/project.pbxproj
- KWNoticeKit/KWNoticeKit.h
> Modularization - add KWNoticeKit

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/AppDelegate.swift
- KWNotice/Info.plist
- KWNotice/KWNoticeApp.swift
- KWNotice/Setting/Setting.swift
- KWNotice/Setting/SettingView.swift
- KWNotice/Setting/Topic.swift
- KWNotice/Setting/TopicSubscriber.swift
same as commit histories
https://github.com/kw-notice/kw-notice-ios-v1/issues/9
> Develop topic subscription

- KWNotice.xcodeproj/project.pbxproj
- KWNoticeKit/Model/Endpoint.swift
- KWNoticeKit/Network/APIRequest+APIError.swift
- KWNoticeKit/Network/APIRequest.swift
> Develop KWNoticeKit Network feature

- KWNotice.xcodeproj/project.pbxproj
- KWNoticeTests/KWNoticeTests.swift
> Develop Test Module

- KWNotice.xcodeproj/project.pbxproj
- KWNoticeKitTests/EndpointTests/EndpointTest.swift
> Test Endpoint

- KWNotice.xcodeproj/project.pbxproj
- KWNoticeKit/DataStore/KWHome/KWHomeDataStore.swift
- KWNoticeKit/DataStore/KWHome/KWHomeDataStoreProtocol.swift
- KWNoticeKit/Model/KWHomeNotice.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepository.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepositoryProtocol.swift
- KWNoticeKitTests/RepositoryTests/KWHomeRepositoryTest.swift
- KWNoticeKitTests/TestExtensions/Random+.swift
- KWNoticeKitTests/TestExtensions/TestKWHomeDataStore.swift
> Develop KW Home Domain Tests + Implementations

- KWNotice.xcodeproj/project.pbxproj
- KWNoticeKit/DataStore/SWCentral/SWCentralDataStore.swift
- KWNoticeKit/DataStore/SWCentral/SWCentralDataStoreProtocol.swift
- KWNoticeKit/Model/SWCentralNotice.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepository.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepositoryProtocol.swift
- KWNoticeKitTests/RepositoryTests/SWCentralRepositoryTest.swift
- KWNoticeKitTests/TestExtensions/TestSWCentralDataStore.swift
> Develop SWCentral Domain Tests + Implementation

- KWNotice/Setting/TopicSubscriber.swift
> Fix subscription method

- KWNoticeKit/DataStore/KWHome/KWHomeDataStore.swift
- KWNoticeKit/DataStore/SWCentral/SWCentralDataStore.swift
from https://github.com/kw-notice/kw-notice-ios-v1/issues/19
> add: public initializer for data store

- KWNoticeKit/DataStore/KWHome/KWHomeDataStore.swift
- KWNoticeKit/DataStore/KWHome/KWHomeDataStoreProtocol.swift
- KWNoticeKit/DataStore/SWCentral/SWCentralDataStore.swift
- KWNoticeKit/DataStore/SWCentral/SWCentralDataStoreProtocol.swift
- KWNoticeKit/Model/KWHomeNotice.swift
- KWNoticeKit/Model/SWCentralNotice.swift
- KWNoticeKit/Network/APIRequest+APIError.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepository.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepositoryProtocol.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepository.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepositoryProtocol.swift
- KWNoticeKitTests/RepositoryTests/KWHomeRepositoryTest.swift
- KWNoticeKitTests/RepositoryTests/SWCentralRepositoryTest.swift
- KWNoticeKitTests/TestExtensions/TestKWHomeDataStore.swift
- KWNoticeKitTests/TestExtensions/TestSWCentralDataStore.swift
from https://github.com/kw-notice/kw-notice-ios-v1/issues/27
add https://github.com/kw-notice/kw-notice-ios-v1/issues/25
> Develop domain async

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/Components/AlertPublishableObject.swift
- KWNotice/Notice/KWHomeNotice/KWHomeNoticeView.swift
- KWNotice/Notice/KWHomeNotice/KWHomeNoticeViewModel.swift
- KWNotice/Notice/NoticeView.swift
- KWNoticeKit/Model/KWHomeNotice.swift
- KWNoticeKit/Model/SWCentralNotice.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepository.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepository.swift
- KWNoticeTests/ViewModel/KWHomeNoticeViewModelTest.swift
> Develop KW Notice presenter

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/App/AppDelegate+.swift
- KWNotice/App/AppDelegate.swift
- KWNotice/App/CoreData/Notification+CoreDataClass.swift
- KWNotice/App/CoreData/Notification+CoreDataProperties.swift
- KWNotice/App/CoreData/Notification.xcdatamodeld/Notification.xcdatamodel/contents
- KWNotice/Components/Extensions/Date+.swift
- KWNotice/View/Setting/SavedNotificationView.swift
> Hotfix Handle Notification, add Copy feature

- KWNotice.xcodeproj/project.pbxproj
- KWNotice.xcodeproj/xcshareddata/xcschemes/KWNoticeKit.xcscheme
- KWNoticeKit/DataStore/Favorite/FavoriteNoticeDataStoreProtocol.swift
- KWNoticeKit/DataStore/Favorite/LocalFavoriteNoticeDataStore.swift
- KWNoticeKit/Model/Favorite/Favorite+CoreDataClass.swift
- KWNoticeKit/Model/Favorite/Favorite+CoreDataProperties.swift
- KWNoticeKit/Model/Favorite/FavoriteNotice.xcdatamodeld/FavoriteNotice.xcdatamodel/contents
- KWNoticeKit/Repository/Favorite/FavoriteNoticeRepository.swift
- KWNoticeKit/Repository/Favorite/FavoriteNoticeRepositoryProtocol.swift
- KWNoticeKitTests/RepositoryTests/FavoriteNoticeRepositoryTest.swift
- KWNoticeKitTests/TestExtensions/TestFavoriteNoticeDataStore.swift
> Develop favorite core data

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/Components/NotificationCell.swift
- KWNotice/KWNoticeApp.swift
- KWNotice/View/Favorite/FavoriteView.swift
- KWNotice/View/Favorite/FavoriteViewModel.swift
- KWNotice/View/KWHomeNotice/KWHomeNoticeView.swift
- KWNotice/View/KWHomeNotice/KWHomeNoticeViewModel.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeView.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeViewModel.swift
- KWNoticeKit/DataStore/Favorite/LocalFavoriteNoticeDataStore.swift
- KWNoticeKit/Repository/Favorite/FavoriteNoticeRepository.swift
- KWNoticeKit/Repository/Favorite/FavoriteNoticeRepositoryProtocol.swift
> Develop favorite presenter

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/Components/NotificationCell.swift
- KWNotice/View/KWHomeNotice/KWHomeNoticeViewModel.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeViewModel.swift
- KWNoticeKit/Extension/String+.swift
- KWNoticeKit/Model/KWHomeNotice.swift
- KWNoticeKit/Model/SWCentralNotice.swift
> Develop date parse

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/Components/NotificationCell.swift
- KWNotice/Components/SafariView.swift
- KWNotice/Info.plist
- KWNotice/Localization/ko.lproj/Localizable.strings
- KWNotice/View/Favorite/FavoriteView.swift
- KWNotice/View/KWHomeNotice/KWHomeNoticeView.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeView.swift
- KWNotice/View/Setting/Setting.swift
- KWNotice/View/Setting/SettingView.swift
- KWNoticeKit/DataStore/Favorite/LocalFavoriteNoticeDataStore.swift
- KWNoticeKit/Model/Favorite/Favorite+CoreDataProperties.swift
- KWNoticeKit/Model/Favorite/FavoriteNotice.xcdatamodeld/FavoriteNotice.xcdatamodel/contents
> Develop select browser

- KWNotice.xcodeproj/project.pbxproj
- KWNotice/View/KWHomeNotice/KWHomeNoticeView.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeView.swift
- KWNotice/View/Setting/Setting.swift
- KWNotice/View/Setting/SettingView.swift
> Develop setting permission

- KWNotice/View/Favorite/FavoriteView.swift
> add: fix placeholder text

- KWNotice/View/Favorite/FavoriteViewModel.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepository.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepository.swift
> Fix Ignore Case when searching

- KWNotice.xcodeproj/project.pbxproj
- KWNotice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KWNotice/Components/NoSearchResultView.swift
- KWNotice/View/Favorite/FavoriteView.swift
- KWNotice/View/Favorite/FavoriteViewModel.swift
- KWNotice/View/KWHomeNotice/KWHomeNoticeView.swift
- KWNotice/View/KWHomeNotice/KWHomeNoticeViewModel.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeView.swift
- KWNotice/View/SWCentralNotice/SWCentralNoticeViewModel.swift
- KWNotice/View/Setting/SettingView.swift
- KWNoticeKit/Extension/String+.swift
- KWNoticeKit/Model/Favorite/Favorite+CoreDataProperties.swift
- KWNoticeKit/Model/Notice/KWHomeNotice.swift
- KWNoticeKit/Model/Notice/SWCentralNotice.swift
- KWNoticeKit/Repository/Favorite/FavoriteNoticeRepository.swift
- KWNoticeKit/Repository/KWHome/KWHomeRepository.swift
- KWNoticeKit/Repository/SWCentral/SWCentralRepository.swift
https://github.com/kw-notice/kw-notice-ios-v1/issues/53
> Fix Entire Search Algorithms

- KWNotice/Components/NotificationCell.swift
> Fix problem: VStack in ForEach has no equal width
